.eslintrc.js

This turns off `import/prefer-default-export`, as it can lead to the same function having multiple names in the code base, and also doesn't allow for a second export to be added to a module.
It also disables a few rules not needed with the formatting being strictly checked.

chore: Update ESLint configuration

---

src/test-utils.ts

This improves the `render()` helper so that it returns an HTMLElement instead of an Element. This makes the return value compatible with various Testing Library functions.

test: Make render() return HTMLElement

---

.github/workflows/lint-and-test.yml

This moves the fixup! commit check to a separate job, so the reason for a workflow failure is clearer.

ci: Move fixup! check to a separate job

---

examples-server/serve.ts
src/lib/utils.ts

This updates the last two imports that weren't using the [`node:` protocol](https://nodejs.org/api/esm.html#esm_node_imports) to use the protocol, for clarity and future compatibility.

chore: Use node: protocol for Node.js imports

---

.github/workflows/codeql.yml

This adds a GitHub code scanning GitHub Actions workflow. This is the same as used in MOD.UK Design System.
See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning for more details.

ci: Add GitHub code scanning

---

src/lib/__tests__/utils.test.ts

This PR Parametrised the addCustomMODUKClass test to test targeting a path. 
I would appreciate feedback on the method here.
The createParams function creates the arguments if nothing is set  `options`  I retuned as an empty object. This is done so I can test the default options.
```ts
const createParams = (path?: string) => {
const propertyPath = path || "classes";
const options = path ? { path } : {};
return [propertyPath, options];
};
it.each([createParams(), createParams("inner.classes")])(
"test %s",
(path, options) => {
expect(addCustomMODUKClass(params, "moduk-custom", options)).toHaveProperty(
path,
"moduk-custom a-class"
);
}
);
//or
it.each(["classes", {}, "inner.classes", { path: "inner.classes" }])(
"test %s",
(path, options) => {
// test code
}
);
```
Test results

test: Parametrised addCustomMODUKClass test

---

.github/workflows/lint-and-test.yml

As the end-to-end tests are now taking about four minutes to run on GitHub Actions, this changes the GitHub Actions workflow so that three shards are used.
Results are reported independently for each shard.

ci: Use sharding when running end-to-end tests

---

.release-it.js
commitlint.config.js

By default, commitlint doesn't handle types containing a hyphen.
This configures a custom `headerPattern` to make it work. See https://github.com/conventional-changelog/commitlint/issues/2694 for more detail (the regex used was based on the current default).
To test locally, you can run e.g. `echo 'deps-dev: fff' | commitlint`.

chore: Fix commitlint parsing of deps-dev type

---

src/nunjucks/moduk/components/details/__tests__/macro.test.js
src/nunjucks/moduk/components/details/__tests__/macro.test.ts
src/nunjucks/moduk/components/details/macro.njk
src/nunjucks/moduk/components/inset-text/__tests__/macro.test.ts
src/nunjucks/moduk/components/inset-text/macro.njk
src/nunjucks/moduk/components/notification-banner/__tests__/macro.test.ts
src/nunjucks/moduk/components/notification-banner/macro.njk
src/nunjucks/moduk/components/panel/__tests__/macro.test.ts
src/nunjucks/moduk/components/panel/macro.njk

This makes various existing components work correctly when a [call block](https://mozilla.github.io/nunjucks/templating.html#call) is used.
The only other component that supports call blocks is error summary (which we haven't implemented yet).

fix: Add support for call blocks to various components

---

package.json

This configures the `files` property in `package.json` to avoid unwanted files being included in the published package.

build(npm): Configure files to publish

---

.github/actions/prepare-environment/action.yml

The registry URL needs to be explicitly set when using the setup-node action as this configures npm to use the NODE_AUTH_TOKEN environment variable for authentication (via a `.npmrc` file).

ci: Fix npm publish step in release workflow

---

.github/dependabot.yml

Dependabot currently seems to only update `package-lock.json` (and not `package.json`) for dev dependencies.
This configures [`versioning-strategy`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy) to hopefully make it update `package.json` as well.

ci(dependabot): Set npm versioning-strategy to increase

---

package-lock.json
package.json

This updates tsconfig-paths and hence json5 via an override to resolve a security alert being flagged by `npm audit`.

chore(deps): Update tsconfig-paths and json5 via override

---

package-lock.json
package.json

This removes the `tsconfig-paths` override, as the security fix to `json5` (a dependency of `tsconfig-paths`) has now been backported.

chore(deps): Remove tsconfig-paths override

---

README.md
examples-site/example.njk
package.json
vite.config.ts

This updates the name of the client bundle from `MODUK.umd.js` and `MODUK.mjs` to `moduk-frontend.umd.js` and `moduk-frontend.mjs` so that it has a more meaningful and conventional name.
It also corrects the `./dist/` package.json exports entry – it should have an asterisk in it: https://nodejs.org/api/packages.html#subpath-patterns (doesn't seem to matter for Webpack, but does for Node).

feat: Rename client JavaScript bundle

---

package-lock.json
package.json

This PR changes govuk-frontend to a peer dependency.

fix: Make govuk-frontend a peer dependency

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.yml

This adds issue form templates for bugs and feature requests.
Inspiration has been drawn from other repos, including GOV.UK Frontend.
I've also put the forms in a test repo, so they can been seen here: https://github.com/jpveooys/github-actions-testing-v2/issues/new/choose
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms and https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema for details on the schema for the YAML file.

chore(GitHub): Add issue form templates

---

package.json

When `@playwright/test` is updated by Dependabot, we tend to have problems as `@axe-core/playwright` has a dependency on `playwright` and the versions get out of sync.
This adds an override to make sure `@axe-core/playwright` uses the same version of Playwright as the project to make updates less painful.

chore(deps): Ensure consistent Playwright version is used

---

.github/workflows/release.yml
package-lock.json
package.json

As the library has now gone through internal testing, this makes the release workflow release normal, non-alpha versions. This will eliminate any related friction when testing with users.
The ability to release an alpha version has been removed completely, as it doesn't fit in with the automated release process.
I've given this a quick test in https://github.com/jpveooys/github-actions-testing-v2.
This also pins `govuk-frontend` to a fixed version, as parts of it are bundled so it doesn't make sense to allow a different version of it to be used.

ci(release): Release non-alpha versions only

---

dprint.json
package.json

This:
- updates the lint-staged config to format before linting. This makes more sense as formatting can fix things flagged by the linter, and the linter doesn't modify files
- adds missing file extensions to the lint-staged config
- simplifies the file patterns in `dprint.json`, as these were more complicated than necessary
- adds `.mts` to `dprint.json` as well
- updates all dprint plugins
dprint plugins were updated using `dprint config update`.
`dprint output-file-paths` can be used to check which files are being checked by dprint.

Update lint-staged and dprint configurations

---

src/css/_colour-palette.scss
src/css/_variables.scss
src/css/index.scss

This adds a `moduk-colour()` function and additional colours to the Sass framework.
(We may want to think about how to unit test Sass functions if we start adding more.)

feat(sass): Add `moduk-colour` function and additional MOD colours

---

src/nunjucks/moduk/components/checkboxes/__examples__/default.njk
src/nunjucks/moduk/components/checkboxes/__examples__/not-as-page-heading.njk
src/nunjucks/moduk/components/checkboxes/__examples__/small.njk
src/nunjucks/moduk/components/checkboxes/__examples__/with-conditional-reveal.njk
src/nunjucks/moduk/components/checkboxes/__examples__/with-error-message.njk
src/nunjucks/moduk/components/checkboxes/__examples__/with-item-hint.njk
src/nunjucks/moduk/components/checkboxes/__examples__/with-none-option.njk

This PR makes the example ids unique for use in the guidance site.

chore(checkboxes): Make example `id` attributes unique

---

package-lock.json
src/css/_variables.scss

There was a typo which meant Helvetica Neue wasn't used when it was available.

fix(styles): Correct typo in font-family

---

src/css/_variables.scss

This makes Helvetica the first option instead of Helvetica Neue, as per the design position.

feat(styles): Update font-family

---

commitlint.config.js

This required an update to the commitlint config to add support for using exclamation mark to flag breaking changes.

release!: Mark next release as version 1.0.0

---

README.md
docs/CONTRIBUTING.md
docs/creating-a-pull-request.md
docs/local-development.md

This updates the README with the content written for v1.0.0 and moves the development info in the README to the contributing docs.
Won't merge this until the guidance site is live but have opened it up for review now. Would suggest browsing the repo as of the commit for that: https://github.com/defencedigital/moduk-frontend/tree/306f04663b1873c269791cc29e85d039008c28b9

docs: Update README and contribution docs

---

tsconfig.json

`examples-site/dist` wasn't being excluded when `npm run lint:types` ran, causing incorrect failures to be reported.

chore(lint-types): Exclude examples-site/dist

---

package-lock.json
package.json
src/css/__tests__/_colour-palette.test.scss
src/css/__tests__/index.test.ts
src/css/_colour-palette.scss

This expands the existing `moduk-colour` Sass function to:
- add the full set of MOD.UK colours
- add the ability to get 80%, 60%, 40% and 20% tints
The existing colours have been maintained to preserve backwards compatibility, and moved to a separate map specifically for legacy colours.
Unit tests using the sass-true library have also been added. These run along with the rest of the unit test suite (using vitest).
(Note there is no way to test `#error` uses, as it terminates Sass compilation.)

feat(styles): Add full MOD.UK colour palette

---

package-lock.json
package.json

`@types/node` wasn't installed, even though it's referenced in `tsconfig.json`. I believe this was just an oversight.

deps-dev: Add missing @types/node dependency

---

package.json

This resolves a problem where it wasn't possible to import the Sass when using Vite by adding This adding `./src/css/*` to the exports listed in `package.json`.
(Previously, importing the Sass would fail with `Error: Missing "./src/css/index.scss" specifier in "@moduk/frontend" package`.)

fix(exports): Add `./src/css/*` to exports

---

package-lock.json
package.json
src/react/back-link/__examples__/default.tsx
tsconfig.json
webpack-react.config.ts

This updates the `files` and `exports` package.json properties so that the React examples are included in the built package, and can be resolved or imported from the https://github.com/defencedigital/moduk-frontend-guidance-site/.
It also makes the React examples use external imports so that they can serve as standalone examples and be reused for the code snippets. This required configuring aliases in Webpack and TypeScript.

build: Include React examples in built package

---

.github/dependabot.yml

This enables grouped updates for a few of the main groups of dependencies that are normally updated together.
I haven't included babel-loader and the babel plugins in the babel group for now, as we probably wouldn't want to group those for major updates.

ci(dependabot): Add grouped updates

---

package-lock.json
package.json

This updates GOV.UK Frontend to [version 4.7.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.7.0).

feat: Update GOV.UK Frontend to version 4.7.0

---

src/react/header/HeaderNavigationItem.tsx
src/react/header/HeaderNavigationLink.tsx
src/react/header/__examples__/with-service-name-and-navigation.tsx
src/react/header/__tests__/Header.test.tsx
src/react/header/index.ts
src/react/index.ts

The React version of the header component was missing native support for router links. This adds in a similar way to other components.

feat(header): Add support for router links to React component

---

.github/actions/merge-playwright-reports/action.yml
.github/workflows/lint-and-test.yml
.gitignore
package-lock.json
package.json
playwright.config.ts

This updates to Playwright 1.37.0 and makes use of [new functionality to merge reports across shards](https://playwright.dev/docs/test-sharding#merging-reports-from-multiple-shards). The number of shards for the e2e tests was also increased by one, and sharding was added to the visual regression tests (two shards only).

ci(e2e): Merge Playwright shard reports

---

src/react/phase-banner/PhaseTag.tsx

The React PhaseTag component was using `forwardRef`, but wasn't actually forwarding the ref.

fix(phase-banner): Forward ref in PhaseTag

---

src/react/details/Details.tsx
src/react/details/__examples__/default.tsx
src/react/details/__examples__/open.tsx
src/react/details/index.ts
src/react/index.ts

This adds a React implementation of the details component.
The GOV.UK JavaScript for this component is a ponyfill for IE. It is not loaded as React 18 does not work with IE (the JavaScript has also been removed for GOV.UK Frontend 5.0.0).

feat(details): Add React implementation

---

src/react/MODUKBody/MODUKBody.tsx
src/react/accordion/Accordion.tsx
src/react/accordion/AccordionItem.tsx
src/react/back-link/BackLink.tsx
src/react/header/Header.tsx
src/react/header/HeaderNavigationItem.tsx
src/react/header/HeaderNavigationLink.tsx
src/react/internal/Link/Link.tsx

Some components were missing doc comments. This adds them.

docs: Add missing docs to React components

---

src/react/accordion/Accordion.tsx
src/react/accordion/__tests__/Accordion.test.tsx

IDs for accordion items nested in a fragment weren't generated correctly, as those items weren't encountered when mapping over the accordion's children. This flattens the accordion's children before rendering to avoid that problem.

fix(accordion): Fix ID generation of nested items in React component

---

src/react/internal/Link/Link.tsx

The return type of `LinkComponent` was inconsistent with `ForwardRefRenderFunction`, and this is flagged by TypeScript 5.2.

fix: Correct React LinkComponent type

---

.github/workflows/check-fixups.yml
.github/workflows/lint-and-test.yml
.github/workflows/release.yml

This moves the fixup check to a separate workflow, in line with https://github.com/defencedigital/moduk-frontend-guidance-site – this separates it out in email notifications etc.
This also switches back to the `ubuntu-latest` runner, as `ubuntu-22.04` was only used temporarily before 22.04 was promoted to latest.

ci: Move fixup check to separate workflow

---

.github/workflows/check-fixups.yml

Since 'Check for fixup! commits' is a required check, the workflow needs to run on release branches even if the job is skipped.

ci: Run fixup workflow on release branches

---

examples-site/react/example-client.tsx
examples-site/react/example.njk
src/react/internal/test-utils/Root.tsx

This makes pages for React examples on the examples site hydrate the html element instead of the entire document.
This seems to resolve some intermittent hydration problems in WebKit on GitHub Actions.

chore: Change hydration root on React example pages

---

.github/workflows/release.yml

Previously if the release workflow failed late in the process (e.g. when running tests) an orphaned tag would remain and need to be manually deleted.
This adds a step to delete the tag automatically in the relevant failure cases. This was tested in https://github.com/jpveooys/github-actions-testing-v2.

ci: Delete tag on release failure

---

package.json

`npm urn` was used in one place instead of `npm run` (the former still works as it's an alias).

chore: Fix npm run typo in package.json

---

package-lock.json

Bumps @babel/traverse to 7.23.2, get-func-name to 2.0.2, and postcss to 8.4.31

deps-dev: Run `npm audit fix`

---

e2e/tests/components/skip-link/default.spec.ts

e2e tests were failing when pressing Tab to focus, so replaced it with .focus()

test(skip-link): Update test to use .focus()

---

package-lock.json
package.json

Warning is shown when users use package with version of node that isn't 16 or 18. Removing this limitation so that all LTS versions can be used

deps(node): Remove node version limitation

---

package-lock.json
package.json

Users are locked into an old version of `govuk-frontend`

deps(govuk-frontend): Update `govuk-frontend` to 4.8.0

---

package.json

Allows the `govuk-frontend` peer dependency to be resolved when using versions other than 5.0.0 excatly

fix(govuk-frontend): Allow for compatible `govuk-frontend` versions

---

package-lock.json

Updated `vite` to 5.4.6 and `path-to-regexp` to 6.3.0

deps: resolve dependency vulnerabilities

---

package-lock.json

High security vulnerability fixed by updating `cross-spawn`

deps: fix vulnerability with `cross-spawn`

---

package.json

createNunjucksEnvironment was not being exported correctly

fix: make createNunjucksEnvironment function available

---

package-lock.json

`package-lock.json` needed to be updated following the update to `eslint-plugin-unicorn` to resolve the remaining vulnerability

deps-dev: update `package-lock.json`
